version: '3'

services:
  app:
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:2017
